### ISSUE TITLE
Fearful as the only prediction

### ISSUE THREAD

**Issue by 19MTG04** [PrashanthaTP/audio-emotion-detector#3]

**Comment by 19MTG04** [comment]
For self taken recordings it always returns "fearful". Have you experienced the same? Do you have a solution for this?

**Comment by PrashanthaTP** [comment]
Hello @19MTG04,

I don't remember testing on different kinds of input.
It was only used to verify the inputs from same dataset which was
used for training.

Have you trained your own model or Are you reusing the one provided in repo?
If you are reusing, then what you are observing might be because of how the model was trained.

If I remember correctly, to train the model in the repo,
the dataset taken for training was very small and wasn't diverse.
Also there is no preprocessing step (like noise removal etc)
apart from feature extraction.

I suggest training on your own, taking a larger portion of the dataset
or adding noise for some inputs manually, or using different ml/deep learning technique.

These suggestions might look generic, but my knowledge limited in this field.

**Comment by 19MTG04** [comment]
Hi, thanks for the reply. I trained my own model with a larger part of the dataset and put svm.SVC(C=1000, gamma='scale') to get the behavior I needed.
